### ISSUE TITLE
Show bounced mails in statistics

### ISSUE THREAD

**Issue by AltarBeastiful** [bramley/phplist-plugin-smtp2go#1]
Would it be possible to show bounces elsewhere that the event log ?

I'd like to have bounce statistics as it allows phplist to remove those emails from suscribers lists. This is really usefull for using mail delivery services that monitors your bounce rate.

Willing to do the dev myself, just wondering if this was a limitation in phplist plugin api itself.

**Comment by bramley** [comment]
Does smtp2go send "real" bounces, which phplist can handle through its normal bounce processing, or does it only reject sending to an email address to which it cannot deliver?

I don't use SMTP2GO (I developed this plugin for a client) so don't really know much about how it handles bounces apart from  limited documentation https://support.smtp2go.com/hc/en-gb/articles/223087687-Hard-Soft-Bounces-and-Rejected-Emails

It might be possible to log any smtp2go errors to a single log file (probably just a plain text file) instead of to the event log.
